slam_toolbox_node:
  ros__parameters:
    mode: "mapping"  # Slam mode
    odom_frame: "odom"
    map_frame: "map"
    base_frame: "base_link"  # Adjust to your robot's base frame
    use_scan_matching: true
    use_odom_data: true
    use_laser: true
    min_scan_angle: -3.14  # Full LiDAR FOV
    max_scan_angle: 3.14
    resolution: 0.05  # Map resolution
    max_laser_range: 20.0  # Max pointcloud range
    minimum_time_interval: 0.5  # Time between scans
    transform_timeout: 0.0
    scan_topic: "/scan_filtered"  # Output from pointcloud_to_laserscan
    odom_topic: "/zed/zed_node/odom"
    scan_qos: "reliable"